Algoritmo "Area_do_Retangulo"
// Descrição   : calculo da area do retangulo
// Autor(a)    : Rodrigo
// Data atual  : 19/09/2017
Var
// Seção de Declarações das variáveis 
comprimento,largura,area:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("qual comprimento do retangulo?")
Leia(comprimento)
escreva (" qual a largura do retangulo")
leia(largura)
area<-comprimento*largura
escreva ("a area é",area)

Fimalgoritmo