Algoritmo "Media_de_3Notas"
// Descrição   : Media de 3 notas
// Autor(a)    : Rodrigo
// Data atual  : 19/09/2017
Var
// Seção de Declarações das variáveis 

nota1,nota2,nota3:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

   Escreva("qual e nota 1")
   leia (nota1)
   Escreva ("qual e nota 2")
   leia (nota2)
   Escreva ( "qual e nota 3")
   leia (nota3)
   media <- nota1+nota2+nota3/3
   Escreva ("a media é:",media)


Fimalgoritmo