Algoritmo "Nadadores"
// Autor(a)    : Rodrigo
// Data atual  : 28/09/2017
Var
idade:inteiro
Inicio

Escreva ("qual a idade")
leia (idade)
Escolha (idade)
caso 0 ate 4
escreval ("nao tem categoria")
caso 5 ate 7
escreval ("infantil A")
caso 8 ate 10
escreval ("infantil B")
caso 11 ate 13
escreval (" Juvenil A")
caso 14 ate 17
escreval ("Juvenil B")
caso 18 ate 200
Escreval ("senior")
fimescolha

Fimalgoritmo