Algoritmo "Perimetro_do_circulo"
// Descrição   : Calculo do perimetro do circulo
// Autor(a)    : Rodrigo
// Data atual  : 19/09/2017
Var
// Seção de Declarações das variáveis 

Diametro,perimetro:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Escreva ("qual o diametro")
leia (diametro)
Perimetro<- 3.14 * diametro
Escreva (" o perimetro é:",perimetro)

Fimalgoritmo